name: tests

on:
  - push
  - pull_request
  - workflow_call

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.8'
          - '5.10'
          - '5.12'
          - '5.14'
          - '5.16'
          - '5.18'
          - '5.20'
          - '5.22'
          - '5.24'
          - '5.26'
          - '5.28'
          - '5.30'
          - '5.32'
          - '5.34'
          - '5.36'
          - '5.38'
          - latest
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Regular tests
        if: ${{ matrix.perl-version != 'latest' }}
        run: |
            cpanm --installdeps --notest .
            perl Makefile.PL
            make test

      - name: Coverage report
        if: ${{ matrix.perl-version == 'latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            cpanm --installdeps --notest . Devel::Cover Devel::Cover::Report::Coveralls
            perl Makefile.PL
            cover -test +ignore 'Makefile.PL' -report coveralls
